
import React, { Component } from 'react';
import HeaderLogo from "../assets/DesktopWebsite/top_logo.png";
import './DesktopCareers.css'

export class Policy extends Component {
    constructor(props){
        super(props)
    }

    render(){
        return (
        <div className='careers-page'>
            <a href="/" ><img src={HeaderLogo} className='header-logo'/></a>
            <div className='content-container'>
                <span className='content-heading terms-heading'>PRIVACY POLICY</span>
                <div className='cards-container terms-para'>
                    <h3>1. INTRODUCTION </h3>
                    <p>
                    (a) This Privacy Policy covers information CRAVE INFORMATION PRIVATE LIMITED (<b>"Company"</b>) collects from you (<b>“You” or “User”</b>) from the website <a href="https://at.social">www.at.social</a> (<b>“Website”</b>). 
                    </p>
                    <p>
                    (b) This Privacy Policy should be read in conjunction with the Terms of Use (“Terms”). Personal Information of a User(s) is collected if the User(s) registers with the Website, accesses the Website or takes any action on the Website or uses or accesses the Content Services as defined in the Terms. The terms ‘Personal Information’, ‘Sensitive Personal Data’ and ‘Information’ shall have the meaning ascribed to it under the applicable laws in India. Your use of our services offered on the Website is constructed to mean that You consent to the Company’s collection, storage, processing and transfer of your Personal Information or Sensitive Personal Data or Information in accordance with this Privacy Policy and You consent to the terms and conditions of this Privacy Policy. 
                    </p>
                    <p>(c) The Company respects your privacy and values the trust you place in the Company by providing Personal Information as required, and this Privacy Policy sets out the policies and practices in relation to the collection, use, disclosure and protection of the Personal Information of the Users of the Website. </p>
                    <p>(d) All capitalized terms and terms used in the Terms which are also used herein below shall be ascribed the same meaning as set out in the Terms, unless repugnant to the context herein or otherwise have been specifically defined herein. </p>
                    <h3>2. APPLICABILITY OF PRIVACY POLICY </h3>
                    <p>This Privacy Policy shall be applicable only to the use and disclosure of information on the Website. This Privacy Policy does not apply to information collected by or through any other medium, collected offline or by any other person and/or entity other than the Website or any other website whose link might be present on the Website for example, if you click on a link of another website displayed on the Website, it may direct you to the other website or application in which case this Privacy Policy shall not be applicable. 
</p>
                    <h3>3. MEANING OF PERSONAL INFORMATION AND PERSONAL SENSITIVE DATA</h3>
                    <p>Personal information shall mean any information that relates to a natural person, which either directly or indirectly, in combination with other information available or likely to be available with the Website, is capable of identifying such person or when combined with other information can be used to identify such person. Personal sensitive data includes Personal Information such as (i) Your password; (ii) financial information such as Bank account or credit card or debit card or other payment instrument details; (iii) physical, physiological and mental health condition; (iv) sexual orientation; (v) medical records and history; (vi) Biometric information; (vii) any detail relating to the above clauses as provided to body corporate for providing service; and (viii) any of the information received under above clauses by body corporate for processing, stored or processed under lawful contract or otherwise.</p>
                    <h3>4. USER INFORMATION </h3>
                    <p>(a) The Company shall collect information You provide to the Company. Some of this information may be given voluntarily by the User while availing certain services offered on the Website including free demo services offered by the Company on the Website; or on the Payment Method available on the Website for making payments to the Company; while some information may be collected automatically when the User is viewing Content Services on the Website.</p>
                    <p>(b) Information provided voluntarily- 
The Company may require the You to voluntarily provide information about yourself in the following events:
</p>
                    <p>(i) When you register yourself with the Website. (ii) When you fill out a form/ application to avail any of the Content Services provided by the Company on the Website. (iii) When you communicate with the Company or make a request on the Website; via e-mail, phone or SMS. (iv) When you choose to provide reviews or ratings, taste preferences, account settings, (including preferences set in the "Account" section of our Website), or otherwise provide information to the Company through our service or elsewhere. (v) To evaluate your eligibility for certain types of offers and services. (vi) To conduct a free demo trial. (vii) To perform analytics and conduct customer research, including general market research or surveying our customers' needs and opinions on specific issues, generating sales and traffic patterns, and to analyze advertising effectiveness, both on an anonymous basis (e.g., by aggregating data) or on an individual basis (if legally permissible). 
</p>
                    <p>(c) In any of the aforesaid events, you may be required to provide the following information:</p>
                    <p>(i) Your name; (ii) Date of Birth; (iii) Contact details including postal address, pin code, email address, phone number, residency status; (iv) Identity proofs (e.g. driving license, passport, PAN card, birth certificate, etc.); (v) Personal details such as age, sexual orientation, marital status, occupation, interests and hobbies etc.; (vi) Details of your talent, skill, hobbies; (vii) Work experience; (viii) Ethnicity; (ix) Language; (x) Dialect.</p>
                    <p>(d) You may note that it is possible that the Company may collect Personal Information about You from sources other than yourself, such as forums, blogs, instant messaging, referral program, other users of our Content Services and our business partners. However, any such information shall not be considered to be sensitive, if it is freely available in the public domain, or under the (Indian) Right to Information Act, 2005 or under any other applicable law for the time being in force. </p>
                    <p>(e) Our primary purposes in collecting information including Personal Information or Sensitive Personal Data or Information from You is to allow You to use the Website and various features and Content Services on or in relation to the Website or any Sites contact You for any Content Services provided by the Company or its affiliates or its various service providers or Company business partners and advertisers; to record Your information and details as permitted and required under applicable laws, statutory direction or judiciary orders; to serve various promotion materials and advertising materials to You; and such other uses as provided in the Terms and this Privacy Policy. </p>
                    <p>(f) The Company may also use the Personal Information or Sensitive Personal Data or Information provided by You for content recommendations, transactional emails or to provide You with information, direct marketing, online and offline advertising and other materials regarding products, services and other offers from time to time. 
</p>
                    <p>(g) Information retrieved/collected automatically 
</p>
                    <p>The Company collects information about You and Your use of our service, Your interactions with the Company and the Company’s advertising, as well as information regarding your computer or other device used to access the Website (such as gaming systems, smart TVs, mobile devices, and set top boxes). This information includes: 
</p>
                    <p>(i) Your interactions with our email, push and text messaging; (ii) device IDs or other unique identifiers; (iii) advertising identifiers, such as those on mobile devices, tablets, and streaming media devices that include such identifiers (see the "Cookies and Beacon" section below for more information) (iv) Cookies: Cookies are pieces of data/ information that are sent by a web browser/ website and stored on the hard drive of your computer/ mobile. Cookies are a reliable mechanism for websites to remember the state of the website or activity the User had taken in the past, including clicking particular buttons, logging in, or a record of which pages were visited by the user even months or years ago. The Website may assign a 'cookie' to You, encrypting your information, which may be saved on your computer's hard drive/ mobile while you visit the Website. This will help adjust and track your preferential information every time you visit the Website thereafter. You may note that this Privacy Policy includes 'cookies' that are placed by the Website and does not cover any 'cookie' that may be placed by any third party website. Your internet browser may allow you to not store any cookies on your computer/ mobile or alternatively you may choose to delete the stored cookies from your computer/ mobile; however, you may note that, in such an event your navigation through the Website or access to certain features/ services of the Website may be restricted. (v) Beacons/Bugs: A beacon is a picture file used to keep track of your navigation through a single website or a series of websites. The Company may use such web beacons to study and analyse the usage of the Website. (vi) Usage Details: The Website may also collect details regarding your visits to and navigation through the Website such as your location data, IP address, operating system, browser type, geo-locations other resources that you access etc. 
</p>
                    <h3>5. ELIGIBILITY, USE AND INFORMATION </h3>
                    <p>(a) You are eligible to register and avail the Content Services provided on the Website only if you are an Eligible Person. 
</p>
                    <p>(b) In case the services offered by the Website are for and on behalf of a minor or a child or a person who is not an Eligible Person, the Website must be accessed by only the parents/ legal guardians who have to be competent to contract and act on behalf of such minor or child or person who is not an Eligible Person. Such parents/ legal guardians will be responsible adhering to this User Agreement and for the actions of the minor, child or a person not being an Eligible Person, on whose behalf he/she accesses the Website without any liability whatsoever on the Company. </p>
                    <h3>6. CONSENT GIVEN BY USER </h3>
                    <p>(a) You understand, agree and acknowledge that our collection, storage and processing of your Personal Information or Sensitive Personal Data or Information is for a lawful purpose connected with a function or activity of the Company. You hereby consent to the collection, storage, use, disclosure, transfer, of the Personal Information or Sensitive Personal Data or Information by the Company for the purposes set out herein. You further understand, agree and acknowledge that Your Personal Information which is classified as Sensitive Personal Data or Information as per applicable laws is considered necessary for the Company to provide various services on its Website to You and for Your usage of the Website and other services provided by the Company in relation to the Website and you affirmatively consent to its collection, storage, transfer and processing. </p>
                    <h3>7. PURPOSES FOR COLLECTION AND USAGE OF INFORMATION</h3>
                    <p>(a) Personal and non-personal information collected by the Company, will be used by the Company in handling general enquiries concerning its services, in providing better user interface, making your visit to the Website more user-friendly and without limiting the foregoing, for the following purposes: 
</p>
                    <p>(i) Registering of your account with the Website; (ii) Enabling the access of the Website and use of the services available to Users; (iii) Addressing questions, doubts, queries raised, clarifications and information sought and for addressing technical issues which arise in the Website; (iv) Designing or identifying services, data, information or related products for users; (v) Marketing (including direct marketing) of products/services, send information, materials and offers from the Company; (vi) Meeting the requirements to make disclosure under any law binding on the Website, the Company, its directors, associates or employees, under and for the purposes of complying with any directions or guidelines issued by regulatory or other authorities with which the Website or the Company or any associated entity is expected to comply; (vii) In connection with any exchange of information and verification and authentication of the information that may be provided by the User, to evaluate the eligibility of the User or minor (as the case may be) for certain types of offers, products and services that may be of interest to you and analyse advertising effectiveness. 
(viii) In connection with any system or facility for payment by electronic means or via other communication media in which the Website participates; (ix) To send you alerts, notices, letters, newsletters, offers, response to request and other customer support queries and/or any other communication which may be relevant and vital to the usage of the Website by You; (x) To enable the Company as well as third parties to provide itself or procure from third parties customised information, services, offers and advertisements etc.; (xi) To third party contractors that provide services to the Website; (xii) To internally analyse the performance of the Website, Company's internal technical systems and data; (xiii) To gather demographic data to research, analyse and understand trends and behavioural patterns, to measure and understand the effectiveness of any of the aspects of the services of the Website, to trouble any problems, track your movement, gather broad demographic information for aggregate use and to comply with the applicable law; (xiv) To alert you about potential software compatibility issues and/or for improvement of the Website; (xv) To monitor and administer daily operations and functions of the Website; (xvi) To enforce the "User Agreement" of this Website; (xvii) For all other purposes as may be disclosed when you provide personally identifiable information/sensitive personal data; (xviii) All other incidental and associated purposes relating to the above and any other purpose which a User may from time to time agree. (xix) To determine your general geographic location, provide localized content, provide you with customized and personalized viewing recommendations for movies and TV shows the Company thinks will be of interest to You, determine your Internet service provider, and help the Company quickly and efficiently respond to inquiries and requests; (xx) To prevent, detect and investigate potentially prohibited or illegal activities, including fraud, and enforcing our terms (such as determining free trial eligibility); and (xxi) To analyze and understand our Users, improve our service (including our user interface experiences) and optimize content selection, recommendation algorithms and delivery.</p>
                    <h3>8. DISCLOSURE OF PERSONAL INFORMATION </h3>
                    <p>(a) The Company may disclose/ transfer (whether within or outside India) and/or exchange your Personal Information including your personal data to and/ or with all such persons and/or entities, as may be required for the aforesaid lawful purposes, including but not limited to: </p>
                    <p>(i) Any of its directors, shareholders, associates or employees, or any of its affiliates; (ii) Any agent, contractor or third party service provider who provides administrative, advertising and marketing agencies, telecommunications, computer, financial intermediary, payment or securities clearing or other services to the Company in connection with the Website or the operation of the Company's business and services through the Website; (iii) Any other person under a duty of confidentiality, including any member which has undertaken to keep such information confidential; (iv) Any actual or proposed assignee of the Company or participant or sub-participant or transferee of the Company's rights in respect of the information of the 
User; (v) To any third party such as talent placement agencies when you choose to avail certain services/ facilities offered on the Website. In such an event, the Company does not take any responsibility for any misuse or unwarranted disclosure of such information that may be made by such third party. (vi) Any person to whom the Company is under an obligation to make disclosure under and for the purposes of any guidelines issued by regulatory or other authorities; (vii) As may be required by law or court order or administrative/ government agency or in a situation of national emergency or when the Company believes that an information disclosure is required to protect the Company's rights or those of the Users or any other aspect of the Website and to comply with the legal process without any restrictions; (viii) In any event where the Company has reason to believe that you are in violation of any applicable law, rule or regulation, or interfering with the rights of any other person; (ix) To any potential investor or purchaser of any interest in the Company or Website or any associated entity or in its business in connection with any potential re-organisation, merger or disposal; (x) Any lawyer or other professionals for the preparation of any document or professional advice regarding the above; and (xi) The Company may offer joint promotions or programs that, in order for your participation, will require the Company to share your information with third parties. In fulfilling these types of promotions, the Company may share Your name and other information in connection with fulfilling the incentive. Please note that these third parties are responsible for their own privacy practices. </p>
                    <p>(b) The Company will endeavour to ensure that the third party receiving any Personal Information does not disclose it further and shall observe the same level of data protection as is ensured by the Company in respect of the Website and in consonance with this Privacy Policy. 
</p>
                    <p>(c) Notwithstanding anything contained elsewhere, any personal information including sensitive data may be disclosed by the Company to any third party by an order/ direction under the law for the time being in force, without any consent or other obligation. For instance, Personal Information may be released to an officer making the request if he provides a warrant or a court order requiring such disclosure. 
</p>
                    <p>(d) Where a government agency makes a request to obtain information for the purpose of verification of identity, or for prevention, detection, investigation including cyber incidents, prosecution and punishment of offences, the Company may share the Personal Information without obtaining any prior consent of the User. The Company will be utilising the services of third party service providers such as technical service providers to create and support the Website, third party advertising company etc. The Company may publish or share Your non-Personal Information in order to promote the Website with the Company's affiliates, various third parties and Company's service providers without Your consent. You are informed that the Company's third party service providers may utilise information relating to your usage of the Website in order to provide customised services, offers and advertisements to You. </p>
                    <h3>9. VERIFICATION OF INFORMATION</h3>
                    <p>In the event that you choose to avail any service or facility that may be offered through the Website or put in a request or query with respect to the same, you shall have to register yourself 
with the Company and/ or provide Personal Information about yourself. You may note that the Company may (through its agents/ service providers) contact You either through e-mail, fax, telephone or personal visits for verification/ confirmation of the same. 
</p>
                    <h3>10. OPTION TO WITHHOLD / WITHDRAW </h3>
                    <p>Prior to collection of the Personal Information (including Sensitive Personal Data), the Website may give You an option to withhold the data/ information sought. Further, you may withdraw the consent given to the Company on the Website, by communicating in writing. However, such withholding of information or withdrawal of consent may result in the Company being unable to provide services and facilities through the Website and the Company reserves its right to take appropriate action with respect to any obligations or in relation to any contract under which such Personal Information was sought. It being clarified that such withdrawal of consent shall not affect the permission granted prior to such withdrawal and hence the Company shall not be liable for sharing Personal Information (as stated herein) in any manner whatsoever. 
</p>
                    <h3>11. ACCURACY OF AND ACCESS TO PERSONAL INFORMATION</h3>
                    <p>(a) The Company will not be responsible for the accuracy or authenticity of the Personal Information or Sensitive Personal Data that is provided by You. It is the responsibility of the User to notify the Company through the Website of any changes to their Personal Information. To attain this end, the User may request the Website for reasonable access to, and correction of, their Personal Information collected by the Website by emailing their request/clarification at info@at.social. The Company makes good efforts to provide its Users with reasonable access to their respective Personal Information and shall ensure that any Personal Information found to be inaccurate and brought to the notice of the Company by the User is rectified or amended as feasible. The Company may however before processing such requests, ask the User to identify themselves and the information /data requested to be modified by them in order to avoid repetitive and/or illegitimate requests. The Company shall not be responsible for any delay in updating such information.</p>
                    <p>(b) In the event a User requests the Company to delete his/her Personal Information and/or his account, the Company shall ensure that such Personal Information/ user account is deleted within 36 (thirty-six) hours of receiving such a request. The Company may however before processing such requests, ask the User to identify themselves and the information /data requested to be deleted by them in order to avoid any illegitimate/bogus requests. Once the Personal Information/ user account is deleted, all data in respect thereof shall cease to be accessible to the User, and the Company may thereafter send an email to such User apprising him/her of such deletion. The User may contact the Company by emailing their request on info@at.social. 
</p>
                    <p>(c) It is clarified that, after the deletion of the Personal Information/ User account, the Company shall maintain records of the same for a period of 90 (ninety) days thereafter in a separate restricted and confidential back up after which the same shall be deleted therefrom. It is clarified that even though the Company may maintain records of deleted data for 90 (ninety) days, once the Personal Information/ user account of a particular User has been deleted upon his/her request, the same shall not be retrievable by the User in any manner whatsoever and at any time thereafter. 
</p>
                    <p>(d) The Company may, however, withhold or may not be able to provide information to You for valid reasons including if it: </p>
                    <p>(i) contains references to another User(s); (ii) is subject to legal/ contractual privilege or cannot be disclosed for other legal reasons; (iii) contains confidential commercial/ business information of the Company or other users of the Website; (iv) is not maintained by the Company; (v) was created in the course of a dispute resolution process; (vi) could threaten the life or security of another individual/ entity; (vii) was disclosed under a court order or was disclosed to a government institution as part of an investigation. </p>
                    <h3>12. LINKS TO THIRD PARTY WEBSITES/APPS</h3>
                    <p>You may note that any links to third party websites/ apps are not an endorsement of such third parties, their websites/ apps and/or their products/services by the Company. The Company does not take any responsibility for their privacy policy, terms of use, content, services and products. They may place independent cookies on your computer/mobile or independently contact You, for which the Company or Website shall not be held responsible or liable in any manner whatsoever. The Company encourage you to read individual terms of use and privacy policy of each of these websites before using them and/or disclosing your Personal Information. 
</p>
                    <h3>13. DATA SECURITY </h3>
                    <p>(a) The Company understands the importance of data security and the Company wants the User experience with the Company to be as safe as possible. The Company has implemented reasonable safeguards and precautions to protect Your Personal Information or Sensitive Personal Data or Information, including technical and organizational measures against unauthorized access, improper use, alteration, unlawful or accidental destruction, and accidental loss, both in an online and offline context. </p>
                    <p>(b) The Company has adopted reasonable and best security practices and procedure and the Company maintains technical and organizational security measures and procedures to protect the security of Your Personal Information or Sensitive Personal Data or Information, which are consistent with measures used by other similar websites. 
</p>
                    <p>(c) Please understand that, while the Company strives to protect Your Personal Information or Sensitive Personal Data or Information against potential risks and exposures, there is no absolute security in the online sphere. Hence, the Company asks you to support our IT security efforts by not disclosing any of Your Personal Information or Sensitive Personal Data or Information data on the Website that is particularly sensitive or not required in the specific context. Furthermore, You can help the Company in protecting your personal data by signing off when You finish using login-protected areas of the Website. 
</p>
                    <h3>14. PUBLICATION </h3>
                    <p>The uploading, dealing, handling and/ or using of any Personal Information for any lawful purpose by the Website, including for the purposes and in the manner outlined above shall not constitute 'publication' in any manner. 
</p>
                    <h3>15. REASONABLE SECURITY PRACTICES & PROCEDURES </h3>
                    <p>(a) The Company takes appropriate security measures to protect against unauthorized use, access, alteration and destruction of data; however, the Company does not guarantee that the information provided by You to the Website shall not be intercepted while being transferred over the internet. Access to all Users is password protected and the Website has SSL certification. The Website is also in compliance with International ISO Standard. 
</p>
                    <p>(b) You are responsible for maintaining the confidentiality of your login ID and password and shall not reveal the same to any third party. In the event you believe that your user information has been stolen or compromised, you must contact the Company immediately on info@at.social. The Company shall endeavour to block Your Account or provide restricted access upon being informed of such an event in order to protect Your identity and information. However, the Company shall not be responsible for any unauthorized use/access to Your account or disclosure of any Personal Information by virtue of such an event. 
</p>
                    <h3>16. OPERATION OF THIS WEBSITE</h3>
                    <p>(a) This Website may be operated from India as well as outside India. In the event you are located in any place other than in India, you shall ensure that you comply with the applicable laws in India as well as the local laws or regulations of the territory from which you access the Website or the facilities and services provided by the Website.</p>
                    <p>(b) The Company may transfer information that may be collected by the Company about You, including personal information across borders and from your country or jurisdiction to other countries or jurisdictions around the world. If You are located in any European Union country or United States or other regions with laws governing data collection and use that may differ from Indian laws, please note that we may transfer information, including personal information, to a country and jurisdiction that does not have the same data protection laws as Your jurisdiction. </p>
                    <h3>17. AMENDMENTS/CHANGES TO PRIVACY POLICY </h3>
                    <p>This Privacy Policy may be revised from time to time at the sole discretion of the Company without any advance intimation to You. Your continued use of the Website following such revision or modification shall constitute your acceptance of the revised Privacy Policy. The Company encourages you to periodically review this page for the latest information on our privacy practices and keep yourself informed about the updated Privacy Policies.</p>
                    <h3>18. ENTIRE AGREEMENT</h3>
                    <p>This Privacy Policy and the Terms constitute the entire agreement between You and the Company, and no other agreement, written or oral, exists between You and Company with respect to the Website.</p>
                    <h3>19. DISPUTE RESOLUTION</h3>
                    <p>Any dispute between a User and the Company arising out or in relation to this Privacy Policy, shall be referred to arbitration to be conducted by a sole arbitrator mutually appointed by the Company and the User. However if the Parties are unable to agree on a sole arbitrator within thirty (30) days of reference of dispute to arbitration, then the arbitrator shall be appointed in accordance with the provisions of the Arbitration and Conciliation Act, 1996 or any statutory re-enactment or modification for the time being in force. The seat of arbitration proceedings 
shall be Mumbai, in accordance with the provisions of the Arbitration and Conciliation Act, 1996. The language of arbitration shall be English. The arbitration fees shall be borne by the User. 
</p>
                    <h3>20. GOVERNING LAW AND JURISDICTION </h3>
                    <p>(a) These Privacy Policy shall be governed by the laws of India. (b) Subject to Clause 19 above, the courts in Mumbai shall have exclusive jurisdiction in relation to these Terms. </p>
                    <h3>21. COMPLAINTS</h3>
                    <p>In the event the you are unhappy and or have a grievance with respect to (a) any service/ product or facility that is provided on the Website; and (b) any other activity that may take place on the Website, or if you have any questions, comments, concerns or feedback regarding this Privacy Policy and/or this Website, you may bring the same to the notice of our Grievance Officer, whose details are given below and/or lodge a complaint with the Company. The Company shall take all the necessary steps to address Your questions, comments, concerns to the best of our abilities.</p>
                    <p>Name: Sahil Dewani Email address: sahil@at.social Address: 111- NIbbana CHSL, <br/>Nargis Datt Road, Pali Hill, Bandra (West), 400050 </p>
                    <h3>22. CONTACT US </h3>
                    <p>For general queries, grievances and communication, you may also contact the Company at the same address mentioned in Clause 21 above. 
</p>
                </div>
            </div>
        </div>)
    }
}